config/routes.rb
require 'sidekiq/web'
require 'subdomain'

Rails.application.routes.draw do

  resources :exercises
  class Subdomain
    def self.matches?(request)
      subdomains %w{ www admin } # reserved subdomains
      request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
  end

  constraints Subdomain do
    resources :works
  end

  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :work
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_tenant
  after_destroy :delete_tenant

  has_many :works

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, request_keys: [:subdomain]

  validates :email, uniqueness: true

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end

  def delete_tenant
    Apartment::Tenant.drop(subdomain)
  end

   def self.find_for_authentication(warden_conditions)
    where(:email => warden_conditions[:email], :subdomain => warden_conditions[:subdomain]).first
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :exercises, dependent: :destroy

  accepts_nested_attributes_for :exercises, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, except: :sign_in
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :redirect_to_subdomain

  private

  def redirect_to_subdomain
    return if self.is_a?(DeviseController)
    if current_user.present? && request.subdomain != current_user.subdomain
      redirect_to works_url(subdomain: current_user.subdomain)
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    root_url(subdomain: resource_or_scope.subdomain)
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :subdomain])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :subdomain])
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:name, :sets, :weight, :work_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /works
  # GET /works.json
  def index
    @works = work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @work.exercises.build
    @work = current_user.works.build
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = current_user.works.build(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the whitelist through.
    def work_params
      params.require(:work).permit(:title, :date, exercises_attributes: [:id, :_destroy, :name, :sets, :weight])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def work_author(work)
    user_signed_in? && current_user.id == work.user_id
  end

  def verbose_date(date)
    date.strftime('%B %d, %Y')
  end

  def has_subdomain
    user_signed_in? && current_user.subdomain
  end

  def verify_subdomain_presence
    request.subdomains.present?
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/exercises/_form.html.erb
<%= simple_form_for(@exercise) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :sets %>
    <%= f.input :weight %>
    <%= f.association :work %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sets</th>
      <th>Weight</th>
      <th>Work</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.sets %></td>
        <td><%= exercise.weight %></td>
        <td><%= exercise.work %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Sets:</strong>
  <%= @exercise.sets %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @exercise.weight %>
</p>

<p>
  <strong>Work:</strong>
  <%= @exercise.work %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/home/index.html.erb
<% if !user_signed_in? %>
  <% content_for :hero do %>
  <section class="hero is-medium is-dark home-hero has-text-centered">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Welcome to <%= Rails.configuration.application_name %>!
        </h1>
        <h2 class="subtitle">
          Host your own works and share your results together.
        </h2>
      </div>
    </div>
  </section>
  <% end %>
<% else %>
  <% content_for :hero do %>
  <section class="hero is-dark has-text-centered">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Welcome <%= current_user.name %>!
        </h1>
        <h2 class="subtitle">
          Access your works to take full advantage of the platform.
        </h2>
      </div>
    </div>
     <div class="hero-foot">
      <nav class="tabs">
        <div class="container">
          <ul>
            <li><%= link_to "View all Works", works_path %></li>
          </ul>
        </div>
      </nav>
    </div>
  </section>
  <% end %>
<% end %>

<div class="columns is-multiline">
  <div class="column">
    <div class="content has-text-centered">
      <% if !user_signed_in? %>
        <p class="subtitle is-4">Ready to get in shape? <br />Start hosting your own works and exercises now.</p>
        <% if has_subdomain %>
          <%= link_to "Let's do this", works_path, class: 'button is-dark is-large' %>
        <% else %>
          <%= link_to "Let's do this", new_user_registration_path, class: 'button is-dark is-large' %>
        <% end %>
       <% else %>
        <h3>Recent works</h3>
          <div class="columns is-multiline">
          <% @works.each do |work| %>
           <%= render 'works/work', work: work %>
          <% end %>
         </div>
       <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'works' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

     <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item"><%= link_to 'Create new Work', new_work_path, class: 'button is-dark' if user_signed_in? %></div>
          <div class="navbar-item">
            <div class="field is-grouped">
            <% if user_signed_in? %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <% if has_subdomain || verify_subdomain_presence %>
              <p class="control">
                <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
              </p>
            <% end %>
            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <%= yield :hero %>

  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>

  </body>
</html>

app/views/works/_form.html.erb
<%= content_tag :div,
  id: "work-form",
  data: {
    id: work.id,
    work: work.to_json(except: [:id, :created_at, :updated_at]),
    exercises_attributes: work.exercises.to_json(except: [:work_id, :created_at, :updated_at]),
  } do %>

  <div class="field">
    <div class="control">
      <label class="label">Work Title</label>
      <input type="text" class="input" v-model="work.title" />
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label class="label">Date</label>
      <input type="date" class="input" v-model="work.date" />
    </div>
  </div>

  <h4 class="title is-4 mt3">Exercises</h4>
  <div v-for="(exercise, index) in work.exercises_attributes">
    <div v-if="exercise._destroy == '1'">
      {{ exercise.name }} will be removed. <button v-on:click="undoRemove(index)" class="button is-light">Undo</button>
    </div>
    <div v-else>
      <div class="pa4 bg-light border-radius-3 border">

        <div class="field">
          <div class="control">
            <label class="label">Exercise Name</label>
            <input type="text" v-model="exercise.name" class="input" />
          </div>
        </div>

        <div class="columns">

          <div class="column">
            <div class="field">
              <div class="control">
                <label class="label">Sets</label>
                <input type="text" v-model="exercise.sets" class="input" />
              </div>
            </div>
          </div>

          <div class="column">
            <div class="field">
              <div class="control">
                <label class="label">Weight</label>
                <input type="text" v-model="exercise.weight" class="input" />
              </div>
            </div>
          </div>
        </div>

        <button v-on:click="removeExercise(index)" class="button is-danger">Remove</button>

      </div>
    </div>
    <hr />
  </div>

  <button v-on:click="addExercise" class="button is-dark">Add Exercise</button>

  <hr />
  <button v-on:click="saveWork" class="button is-success is-large mt4">Save Work</button>
<% end %>

app/views/works/edit.html.erb
<div class="columns is-centered">
  <div class="column is-8">
    <h1 class="title is-1">Editing Work</h1>

    <%= render 'form', work: @work %>
  </div>
</div>

app/views/works/index.html.erb
<h1 class="title is-3">Works</h1>

<div class="columns is-multiline">
  <% @works.each do |work| %>
    <%= render "work", work: work %>
  <% end %>
</div>

app/views/works/new.html.erb
<div class="columns is-centered">
  <div class="column is-8">
    <h1 class="title is-3">New Work</h1>

    <%= render 'form', work: @work %>
  </div>
</div>

app/views/works/show.html.erb
<% content_for :page do %>
  <h1 class="title is-1"><%= @work.title %></h1>
  <p><%= verbose_date(@work.date) %></p>

  <table class="table">
    <thead>
      <tr>
        <th>Exercise</th>
        <th># of Sets</th>
        <th>Weight</th>
      </tr>
    </thead>
    <tbody>
    <% @work.exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.sets %></td>
        <td><%= exercise.weight %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Edit Work', edit_work_path(@work), class: "button mt4"  if work_author(@work) %>
<% end %>

<%= render 'page_template' %>